### ISSUE TITLE
PostCSS Config Invalid Object

### ISSUE THREAD

**Issue by sergiocerrutti** [prismicio-community/slice-library-starter-nuxt#5]
Hey there!
After installing this boilerplate, slice machine ran okay, but both Nuxt and Storybook failed at building because of this:
```
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'order'. These properties are valid:
   object { postcssOptions?, execute?, sourceMap?, implementation? }
    at validate (/Users/***/Sites/***/node_modules/schema-utils/dist/validate.js:105:11)
    at Object.loader (/Users/***/Sites/***/node_modules/postcss-loader/dist/index.js:43:29)
```
I don't even know where to see, any idea?

Note: I use Nuxt in a lot of projects, also Storybook, but this never happened to me, that's why I think it could be related to this boilerplate. Thanks!

**Comment by sergiocerrutti** [comment]
I tried again and the error changed to the same but css-loader instead of PostCSS-loader.
I added css-loader to devDependencies and the error changed, but I saw a warning when builidng Nuxt, about the css-loader@^4.2.0 was expected (not the current 6th version), so I added it to my package and the error has been fixed.

**Comment by lihbr** [comment]
Hey, great to hear @sergiocerrutti! One thing you could try also is deleting lock files & node modules, then fetching dependencies again, this may solve this kind of dependency resolving issues ☺️

**Comment by ryanlabar** [comment]
Seeing this issue as well. Started from scratch via `prismic theme --theme-url https://github.com/prismicio-community/slice-library-starter-nuxt --conf sm.json`

**Comment by phillysnow** [comment]
Ah yes, I think this was accidentally removed in some recent updates I've readded this as a dev dependency again :)
